
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
              - GET
              - DELETE
              - OPTIONS
              - PUT
            allowedHeaders:
              - "*"
            allowCredentials: true


      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
            - Method=GET,POST,OPTIONS,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackUri: forward:/orderServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
            - Method=GET,POST,OPTIONS,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackUri: forward:/productServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/PAYMENT/**
            - Method=GET,POST,OPTIONS,PUT
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackUri: forward:/paymentServiceFallBack


